update to 1.1-beta6

diff --git a/packages/setup/scripts/install-drivers b/packages/setup/scripts/install-drivers
--- a/packages/setup/scripts/install-drivers
+++ b/packages/setup/scripts/install-drivers
@@ -139,6 +139,7 @@ dialog --clear --title "$(gettext "Install additional DVB driver")" --menu \
  "Exit" "$(gettext "I do not want to install now.")" \
  "tbs-drivers" "$(gettext "Support all the TBS devices")" \
  "dvbsky-drivers" "$(gettext "Support all the DVBSky devices")" \
+ "linux-media" "$(gettext "DVB drivers for Linux - Original code from LinuxTV org")" \
  "tbs-dvbc-drivers" "$(gettext "Support all the TBS DVB-C devices")" \
  "tbs-atsc-drivers" "$(gettext "Support all the TBS ATSC devices")" \
  "dvbsky-dvbc-drivers" "$(gettext "Support all the DVBSky DVB-C devices")" \
@@ -165,6 +166,12 @@ case "$(cat /tmp/driver.tmp)" in
                 opkg install http://sourceforge.net/projects/openpctv/files/packages/dvbsky-drivers-${kernelver}_Last_${machine}.opk/download --force-overwrite || (echo "Can't download dvbsky-drivers-${kernelver}_Last_${machine}.opk, check your network settings."; exit)
 		HAS_INSTALLED=yes
                 ;;
+  linux-media)	tar -czf /root/kernel_media_$(date +%Y%m%d%H%M%S)_backup.tgz /lib/modules/$kernelver/kernel/drivers/media
+		rm -rf /lib/modules/$kernelver/kernel/drivers/media
+		echo "Download and install linux-media-${kernelver}_Last_${machine}.opk, please wait..."
+		opkg install http://sourceforge.net/projects/openpctv/files/packages/linux-media-${kernelver}_Last_${machine}.opk/download --force-overwrite || (echo "Can't download linux-media-${kernelver}_Last_${machine}.opk, check your network settings."; exit)
+		HAS_INSTALLED=yes
+		;;
   tbs-dvbc-drivers)  tar -czf /root/kernel_media_$(date +%Y%m%d%H%M%S)_backup.tgz /lib/modules/$kernelver/kernel/drivers/media
                 rm -rf /lib/modules/$kernelver/kernel/drivers/media
                 echo "Download and install tbs-dvbc-drivers-${kernelver}_Last_${machine}.opk, please wait..."
